// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtu6iIR6JGSQJrC5nwl6BBizPen6n5dJA',
    appId: '1:783095611032:web:4458d42295f4f46f429aed',
    messagingSenderId: '783095611032',
    projectId: 'poc-auth-1bb70',
    authDomain: 'poc-auth-1bb70.firebaseapp.com',
    storageBucket: 'poc-auth-1bb70.appspot.com',
    measurementId: 'G-73X65FYWY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhIAdLIZI7xBroba1Axzvw3GnOItdGZ7Q',
    appId: '1:783095611032:android:8d919e6e13c4c43e429aed',
    messagingSenderId: '783095611032',
    projectId: 'poc-auth-1bb70',
    storageBucket: 'poc-auth-1bb70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwc3EilDBM6aoXsVwwGVGmeSN-pJrL3sg',
    appId: '1:783095611032:ios:e48da7dedcc01642429aed',
    messagingSenderId: '783095611032',
    projectId: 'poc-auth-1bb70',
    storageBucket: 'poc-auth-1bb70.appspot.com',
    androidClientId: '783095611032-dpnrlndfhf6qko9fjiirq0phab3aq3mo.apps.googleusercontent.com',
    iosClientId: '783095611032-pt5huf91a50r0nmjq3odnvngacr3vcl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocMicrosoftauth',
  );
}
